kind: Service
apiVersion: v1
metadata:
  name: redis-client
  labels:
    app: redis-client
spec:
  selector:
    app: redis-client
  ports:
    - name: redis
      protocol: TCP
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
spec:
  selector:
    matchLabels:
      app: redis-client
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-client
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: redis-client
        image: redis:5-alpine
        stdin: true
        tty: true
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi